source 'https://rubygems.org'

gem 'activerecord', require: 'active_record'
gem 'irb'
gem 'kramdown'
gem 'newrelic-slack-ruby-bot'
gem 'otr-activerecord'
gem 'grape'
gem 'pg'
gem 'rack-server-pages'
gem 'rack-test'
gem 'slack-ruby-bot-server'
gem 'slack-ruby-bot-server-events'
gem 'slack-ruby-block-kit'
gem 'puma'
gem 'rake'
gem 'standalone_migrations'

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'faker'
  gem 'rspec'
  gem 'spec'
  gem 'selenium-webdriver'
  gem 'vcr'
  gem 'webmock'
end