source 'https://rubygems.org'
ruby '3.0.4'

gem 'activerecord', require: 'active_record'
gem 'airrecord'
gem 'clipboard'
gem 'ffi', platforms: %i[mswin mingw] # Required by Clipboard on Windows
gem 'grape'
gem 'irb'
gem 'kramdown'
gem 'newrelic-slack-ruby-bot'
gem 'otr-activerecord'
gem 'pg'
gem 'pry'
gem 'puma'
gem 'rack-server-pages'
gem 'rack-test'
gem 'rake'
gem 'rubocop'
gem 'slack-ruby-block-kit'
gem 'slack-ruby-bot-server'
gem 'slack-ruby-bot-server-events'
gem 'standalone_migrations'
gem 'dotenv'

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'factory_bot'
  gem 'faker'
  gem 'rspec'
  gem 'selenium-webdriver'
  gem 'spec'
  gem 'vcr'
  gem 'webmock'
end
