# frozen_string_literal: true

require_relative 'actions/default'
require_relative 'actions/serin'
require_relative 'actions/english_remainder'
require_relative 'block_actions/morning'
require_relative 'block_actions/evening'
require_relative 'block_actions/who_doesnt_standup-action'
require_relative 'block_actions/remove_messages'
require_relative 'block_actions/excusals/add_excusal'
require_relative 'block_actions/excusals/choice_for_excusal'
require_relative 'block_actions/excusals/remove_excusal'
require_relative 'block_actions/help_interactive'
require_relative 'block_actions/ping_them'
require_relative 'block_actions/who_doesnt_standup-interaction'