# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 10

development:
  <<: *default
  database: wstaniobot
  username: jjdoe
  password: 123444
  host: localhost
  port: 5432
  schema_search_path: myapp,sharedapp,public

test:
  <<: *default
  database: wstaniobot_test
  username: jjdoe
  password: 123444
  host: localhost
  port: 5432
  schema_search_path: myapp,sharedapp,public
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: przyklad_production
  username: jdoe
  password: password
